import { desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { articles } from "@/db/schema";
import { isArticleAdmin } from "@/lib/admin-auth";
import { parseArticleRow, type ArticleInput } from "@/lib/article-types";
import { researchArticles } from "@/lib/research-articles";
import { applyArticleOverrides } from "@/lib/article-overrides";
import { defaultArticles } from "@/lib/default-articles";

function unauthorized(){return Response.json({error:"Unauthorized"},{status:401})}
function normalize(input:Partial<ArticleInput>){return{slug:slugify(input.slug||input.title||""),title:String(input.title||"").trim(),lead:String(input.lead||"").trim(),category:String(input.category||"Patient Education").trim(),readTime:String(input.readTime||"5 min read").trim(),coverImage:String(input.coverImage||"/dr-mohamad-el-haress-portrait.png"),imageAlt:String(input.imageAlt||input.title||"").trim(),takeaway:String(input.takeaway||"").trim(),highlights:JSON.stringify((input.highlights||[]).map(String).filter(Boolean).slice(0,10)),sections:JSON.stringify((input.sections||[]).filter(s=>s.title?.trim()&&s.body?.trim()).slice(0,30)),status:input.status==="published"?"published" as const:"draft" as const,author:String(input.author||"Dr. Mohamad El Haress").trim(),seoTitle:String(input.seoTitle||input.title||"").trim().slice(0,70),metaDescription:String(input.metaDescription||input.lead||"").trim().slice(0,170),keywords:JSON.stringify((input.keywords||[]).map(String).map(value=>value.trim()).filter(Boolean).slice(0,15))}}
function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90)}

export async function GET(){if(!await isArticleAdmin())return unauthorized();const db=await getDb();const rows=await db.select().from(articles).orderBy(desc(articles.updatedAt),desc(articles.id));const managed=rows.map(row=>applyArticleOverrides(parseArticleRow(row as unknown as Record<string,unknown>)));const builtIn=[...defaultArticles,...researchArticles].filter(article=>!managed.some(item=>item.slug===article.slug)).map(applyArticleOverrides);return Response.json({articles:[...managed,...builtIn]})}
export async function POST(request:Request){if(!await isArticleAdmin())return unauthorized();const input=normalize(await request.json() as Partial<ArticleInput>);if(!input.title||!input.slug||!input.lead)return Response.json({error:"Title, slug and introduction are required."},{status:400});if(JSON.parse(input.sections).length===0)return Response.json({error:"Add at least one article section."},{status:400});try{const now=new Date().toISOString();const db=await getDb();const rows=await db.insert(articles).values({...input,publishedAt:input.status==="published"?now:null,updatedAt:now}).returning();return Response.json({article:parseArticleRow(rows[0] as unknown as Record<string,unknown>)},{status:201})}catch(error){const message=error instanceof Error?error.message:"Unable to save article";return Response.json({error:message.includes("UNIQUE")?"This URL slug is already in use.":message},{status:400})}}
export async function PATCH(request:Request){if(!await isArticleAdmin())return unauthorized();const payload=await request.json() as Partial<ArticleInput>&{id?:number};if(!payload.id)return Response.json({error:"Article id is required."},{status:400});const input=normalize(payload);if(!input.title||!input.slug||!input.lead)return Response.json({error:"Title, slug and introduction are required."},{status:400});const db=await getDb();const existing=await db.select().from(articles).where(eq(articles.id,payload.id)).limit(1);if(!existing[0])return Response.json({error:"Article not found."},{status:404});const now=new Date().toISOString();const publishedAt=input.status==="published"?(existing[0].publishedAt||now):null;try{const rows=await db.update(articles).set({...input,updatedAt:now,publishedAt}).where(eq(articles.id,payload.id)).returning();return Response.json({article:parseArticleRow(rows[0] as unknown as Record<string,unknown>)})}catch(error){const message=error instanceof Error?error.message:"Unable to update article";return Response.json({error:message.includes("UNIQUE")?"This URL slug is already in use.":message},{status:400})}}
export async function DELETE(request:Request){if(!await isArticleAdmin())return unauthorized();const id=Number(new URL(request.url).searchParams.get("id"));if(!id)return Response.json({error:"Article id is required."},{status:400});const db=await getDb();await db.delete(articles).where(eq(articles.id,id));return Response.json({ok:true})}
