import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About Mohamad El Haress, MD, FICS | General Surgeon | Surgical Oncologist | Minimally Invasive Surgeon",
  description: "Professional biography of Dr. Mohamad El Haress, including international surgical training, clinical focus, memberships, academic work and patient-care philosophy.",
  alternates: { canonical: "/about" },
  openGraph: { title: "About Dr. Mohamad El Haress", description: "General surgeon and surgical oncologist with international clinical and surgical training.", type: "profile", images: ["/dr-mohamad-el-haress-portrait.png"] },
};

const peerReview = ["International Journal of Surgery", "Annals of Medicine & Surgery", "Cureus Journal of Medical Science", "Journal of Breakthroughs in Medicine & Science (JBMS)"];
const clinicalFocus = ["Complex surgical oncology", "Hepatobiliary & pancreatic surgery", "Gastrointestinal surgery", "Colorectal surgery", "Breast surgery", "Endocrine surgery", "Minimally invasive & laparoscopic surgery", "Minor surgical procedures"];
const profileSchema = { "@context": "https://schema.org", "@type": "ProfilePage", name: "About Dr. Mohamad El Haress", mainEntity: { "@type": "Physician", "@id": "https://drmharess.com/#physician", name: "Dr. Mohamad El Haress", alternateName: ["Dr Mohamad Haress", "Dr Mohammad Haress", "Dr Mohammed Haress"], jobTitle: ["General Surgeon", "Surgical Oncologist"], medicalSpecialty: ["General Surgery", "Surgical Oncology"], knowsAbout: clinicalFocus } };

export default function AboutPage() {
  return <main id="main" className="doctor-profile biography-page">
    <section className="profile-hero"><div className="container profile-hero-grid">
      <div className="profile-hero-copy"><div className="eyebrow light"><span></span>Meet your surgeon</div><h1>Mohamad El Haress,<br/><em>MD, FICS.</em></h1><p className="profile-role">General Surgeon | Surgical Oncologist | Minimally Invasive Surgeon</p><p className="profile-lead">Complex Surgical Oncology · Minimally Invasive Surgery · Hepatobiliary & Pancreatic Surgery</p><div className="profile-actions"><Link className="button white" href="/appointment">Request an appointment <b>→</b></Link><a className="profile-text-link" href="#biography">Read his biography ↓</a></div></div>
      <div className="profile-hero-photo"><Image src="/dr-mohamad-el-haress-portrait.png" alt="Dr. Mohamad El Haress, general surgeon and surgical oncologist" fill sizes="(max-width: 760px) 100vw, 46vw" priority unoptimized/><div className="profile-photo-note"><span>Patient-focused practice</span><strong>Since 2018</strong></div></div>
    </div></section>

    <section className="bio-opening" id="biography"><div className="container bio-opening-grid"><aside><span>Professional biography</span><h2>International experience. Individualized surgical care.</h2></aside><div><p className="bio-lead">Dr. Mohamad El Haress is a General Surgeon and Surgical Oncologist with international clinical and surgical training across Lebanon, the United States, France, India, Egypt and Lithuania.</p><p>His training combines general and minimally invasive surgery with experience in complex surgical oncology, gastrointestinal surgery, colorectal surgery, breast surgery, and hepatobiliary and pancreatic surgery.</p><p>He completed his General Surgery residency at MGH in affiliation with the American University of Beirut.</p></div></div></section>

    <section className="bio-chapter bio-chapter-dark"><div className="container bio-chapter-grid"><div><span>01 · International surgical training</span><h2>Advanced experience across several surgical systems.</h2></div><div className="bio-prose"><p>During his residency training, Dr. El Haress pursued a fellowship in minimally invasive and laparoscopic surgery in New Delhi, India, further developing his experience in advanced laparoscopic techniques and minimally invasive surgical procedures.</p><p>His international surgical training also included experience in colorectal surgery at Alexandria University in Egypt. He subsequently undertook advanced training in hepatobiliary, pancreatic and liver transplant surgery at Greater Paris University Hospitals (AP-HP) in France.</p><p>This work provided exposure to the multidisciplinary management of complex liver, biliary and pancreatic diseases, advanced surgical procedures, and the perioperative care of liver transplant patients.</p></div></div></section>

    <section className="bio-feature"><div className="container bio-feature-grid"><div className="bio-feature-photo"><Image src="/dr-haress-operating.png" alt="Dr. Mohamad El Haress in surgical practice" fill sizes="(max-width:760px) 100vw, 45vw" unoptimized/></div><div><span>02 · Current fellowship</span><h2>Complex Surgical Oncology.</h2><p>Dr. El Haress is currently completing the final year of his fellowship in Complex Surgical Oncology at the American University of Beirut Medical Center (AUBMC).</p><p>His fellowship focuses on the multidisciplinary management and surgical treatment of complex malignancies, particularly gastrointestinal, hepatobiliary, pancreatic, breast and other solid-organ cancers.</p></div></div></section>

    <section className="bio-credentials"><div className="container"><div className="bio-section-title"><span>03 · Professional memberships & certifications</span><h2>Credentials that support continued surgical development.</h2></div><div className="credential-grid"><article><strong>FICS</strong><h3>International College of Surgeons</h3><p>Fellow</p></article><article><strong>ACS</strong><h3>American College of Surgeons</h3><p>Associate Fellow</p></article><article><strong>ESSO</strong><h3>European Society of Surgical Oncology</h3><p>Member</p></article><article><strong>FLS</strong><h3>Fundamentals of Laparoscopic Surgery</h3><p>SAGES program completion</p></article><article><strong>ATLS</strong><h3>Advanced Trauma Life Support</h3><p>Advanced trauma certification</p></article><article><strong>TRACCERT</strong><h3>Healthcare Management for Physicians</h3><p>Gates Group diploma · TRACCERT Canada accredited</p></article></div></div></section>

    <section className="bio-academic"><div className="container bio-academic-grid"><div><span>04 · Academic & scientific contributions</span><h2>Research, publishing and surgical education.</h2></div><div><p>Alongside his clinical practice, Dr. El Haress maintains active involvement in academic surgery, clinical research, scientific publishing and medical education. He has authored and co-authored many peer-reviewed publications appearing in international medical and surgical journals.</p><p>In 2026, Dr. El Haress was a speaker at the Annual Meeting of the Egyptian Society of Laparoscopic Surgery, contributing to the scientific program and exchange of knowledge in minimally invasive and laparoscopic surgery.</p><h3>Peer-review activities</h3><ul>{peerReview.map(item => <li key={item}>{item}</li>)}</ul></div></div></section>

    <section className="bio-focus"><div className="container"><div className="bio-section-title"><span>05 · Clinical & academic focus</span><h2>Comprehensive care for benign and malignant conditions.</h2></div><div className="bio-focus-grid">{clinicalFocus.map((item,index)=><article key={item}><span>{String(index+1).padStart(2,"0")}</span><h3>{item}</h3></article>)}</div></div></section>

    <section className="profile-intro bio-philosophy"><div className="container profile-intro-grid"><div><span className="profile-kicker">Approach to patient care</span><h2>Expertise is essential.<br/><em>Being heard is, too.</em></h2></div><div><blockquote>“Every patient is unique, and every treatment journey deserves clear communication, support and an individualized plan.”</blockquote><p>His approach combines international surgical training, modern minimally invasive techniques, multidisciplinary decision-making and evidence-based oncologic principles. Through continued subspecialty training, scientific research, publications, conference participation, peer-review activities and involvement in international surgical organizations, Dr. El Haress is committed to advancing surgery while providing comprehensive, evidence-based and patient-centered care.</p></div></div></section>

    <section className="profile-closing"><div className="container"><span>Patient-focused surgical care</span><h2>Clear answers. Thoughtful decisions.<br/>A treatment plan built around you.</h2><Link className="button white" href="/appointment">Request an appointment <b>→</b></Link></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(profileSchema)}}/>
  </main>;
}
