import type { Metadata } from "next";
import Link from "next/link";
import { VipTransferForm } from "@/components/vip-transfer-form";

export const metadata: Metadata = { title: "VIP Medical Travel & Aviation Services", description: "Private and commercial medical travel coordination, including multidisciplinary medical escorts and international patient transfers by air or sea.", alternates: { canonical: "/vip-services" } };
const schema = { "@context": "https://schema.org", "@type": "Service", name: "VIP Medical Travel and Aviation Coordination", provider: { "@id": "https://drmohamadelharess.com/#physician" }, areaServed: "International", serviceType: ["Medical escort coordination", "International patient transfer", "Private aviation medical support", "Commercial aviation medical support"] };

export default function VipServices() { return <main id="main" className="vip-page">
  <section className="vip-hero"><div className="container vip-hero-grid"><div><div className="eyebrow light"><span></span>VIP medical travel</div><h1>Specialist medical support,<br/><em>wherever the journey begins.</em></h1></div><div><p>Discreet coordination for patients who need a qualified medical team during private or commercial travel, including international transfers by air or sea.</p><Link className="button white" href="#vip-request">Discuss a transfer <b>→</b></Link></div></div></section>
  <section className="vip-options"><div className="container"><div className="vip-section-head"><span>Two tailored pathways</span><h2>Medical expertise matched to the patient, route and mode of travel.</h2></div><div className="vip-card-grid"><article><b>01</b><span>Patient-provided transport</span><h3>Your private jet or yacht.<br/>Our medical team.</h3><p>When the patient already has access to a private aircraft or vessel, a multidisciplinary medical team can be coordinated according to the patient’s clinical condition and travel requirements.</p><ul><li>Specialists selected for the individual case</li><li>Pre-travel medical assessment and planning</li><li>Medical accompaniment during the journey</li><li>Clinical handover at the destination</li></ul></article><article><b>02</b><span>Complete transfer coordination</span><h3>Transport and medical team,<br/>arranged together.</h3><p>For country-to-country patient transfers, the appropriate aviation option and medical team can be coordinated as one complete plan, subject to clinical assessment and operational availability.</p><ul><li>Private medical aviation coordination</li><li>Commercial aviation medical escort</li><li>Ground-to-air and destination coordination</li><li>International hospital-to-hospital transfer support</li></ul></article></div></div></section>
  <section className="vip-modes"><div className="container"><article><span>Private aviation</span><h2>Privacy, flexibility and clinically planned transport.</h2><p>Suitable aircraft, medical equipment and clinical staffing are considered together based on distance, stability and destination requirements.</p></article><article><span>Commercial aviation</span><h2>Medical support on scheduled flights when appropriate.</h2><p>For stable patients cleared to travel commercially, a medical escort and airline coordination may be arranged according to the individual case.</p></article></div></section>
  <section className="vip-request" id="vip-request"><div className="container vip-request-grid"><div className="vip-request-intro"><span>Confidential request</span><h2>Tell us what the journey requires.</h2><p>Complete the form and a prepared request will open in WhatsApp. Review the message, then press send to contact the coordination team.</p><div><b>01</b><p>Share the route and current patient status.</p></div><div><b>02</b><p>The case is reviewed to identify the appropriate transport and medical team.</p></div><div><b>03</b><p>Availability and the next coordination steps are discussed directly.</p></div></div><VipTransferForm/></div></section>
  <section className="vip-disclaimer"><div className="container"><div><span>Clinical assessment required</span><h2>Every transfer begins with medical review.</h2><p>Service availability, transport method, clinical team and equipment depend on the patient’s condition, route, regulatory requirements and carrier approval. Emergency symptoms require local emergency services.</p></div><Link className="button primary" href="#vip-request">Start a confidential request <b>→</b></Link></div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}} />
</main>; }
