"use client";
import { useEffect,useMemo,useState } from "react";
import type { ArticleInput,ArticleRecord,ArticleSection } from "@/lib/article-types";

const covers=[
  ["Doctor portrait","/dr-mohamad-el-haress-portrait.png"],["Surgical team","/dr-haress-surgery-team.png"],["In surgery","/dr-haress-operating.png"],["Operating room","/dr-haress-operating-room.png"],["Surgical portrait","/dr-haress-surgery-portrait.png"]
];
const empty:ArticleInput={slug:"",title:"",lead:"",category:"Patient Education",readTime:"5 min read",coverImage:covers[0][1],imageAlt:"",takeaway:"",highlights:["","",""],sections:[{title:"",body:""}],status:"draft",author:"Dr. Mohamad El Haress",seoTitle:"",metaDescription:"",keywords:[]};

export default function AdminArticles({userName,signOutHref}:{userName:string;signOutHref:string}){
  const[articles,setArticles]=useState<ArticleRecord[]>([]);const[form,setForm]=useState<ArticleInput>(empty);const[body,setBody]=useState("");const[keywords,setKeywords]=useState("");const[editingId,setEditingId]=useState<number|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[uploading,setUploading]=useState(false);const[notice,setNotice]=useState("");const[query,setQuery]=useState("");
  async function load(){setLoading(true);const response=await fetch("/api/admin/articles",{cache:"no-store"});const payload=await response.json();if(response.ok)setArticles(payload.articles);else setNotice(payload.error||"Unable to load articles.");setLoading(false)}
  useEffect(()=>{void load()},[]);
  const filtered=useMemo(()=>articles.filter(a=>`${a.title} ${a.category}`.toLowerCase().includes(query.toLowerCase())),[articles,query]);
  function update<K extends keyof ArticleInput>(key:K,value:ArticleInput[K]){setForm(current=>({...current,[key]:value}))}
  function autoSlug(title:string){return title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90)}
  function reset(){setEditingId(null);setForm(empty);setBody("");setKeywords("");setNotice("");window.scrollTo({top:0,behavior:"smooth"})}
  function edit(article:ArticleRecord){setEditingId(article.id);setForm({slug:article.slug,title:article.title,lead:article.lead,category:article.category,readTime:article.readTime,coverImage:article.coverImage,imageAlt:article.imageAlt,takeaway:article.takeaway,highlights:article.highlights.length?article.highlights:["","",""],sections:article.sections,status:article.status,author:article.author,seoTitle:article.seoTitle,metaDescription:article.metaDescription,keywords:article.keywords});setKeywords(article.keywords.join(", "));setBody(article.sections.map(section=>`## ${section.title}\n\n${section.body}`).join("\n\n"));setNotice("");window.scrollTo({top:0,behavior:"smooth"})}
  function parseBody(value:string,title:string):ArticleSection[]{const lines=value.split("\n");const sections:ArticleSection[]=[];let current:ArticleSection={title:title||"Article",body:""};for(const line of lines){if(line.trim().startsWith("## ")){if(current.body.trim())sections.push({...current,body:current.body.trim()});current={title:line.trim().slice(3).trim()||"Section",body:""}}else current.body+=`${line}\n`}if(current.body.trim())sections.push({...current,body:current.body.trim()});return sections}
  async function upload(file:File){setUploading(true);setNotice("");const data=new FormData();data.append("image",file);const response=await fetch("/api/admin/article-image",{method:"POST",body:data});const payload=await response.json();if(response.ok){update("coverImage",payload.url);setNotice("Cover image uploaded successfully.")}else setNotice(payload.error||"Unable to upload image.");setUploading(false)}
  async function save(status:"draft"|"published"){setSaving(true);setNotice("");const sections=parseBody(body,form.title);const builtIn=editingId!==null&&editingId<0;const response=await fetch("/api/admin/articles",{method:editingId&&!builtIn?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,keywords:keywords.split(",").map(value=>value.trim()).filter(Boolean),sections,status,id:builtIn?undefined:editingId})});const payload=await response.json();if(response.ok){setNotice(builtIn?"Built-in article converted to an editable article and saved successfully.":status==="published"?"Article published successfully.":"Draft saved successfully.");setEditingId(payload.article?.id??editingId);await load()}else setNotice(payload.error||"Unable to save article.");setSaving(false)}
  async function remove(article:ArticleRecord){if(!confirm(`Delete “${article.title}”? This cannot be undone.`))return;const response=await fetch(`/api/admin/articles?id=${article.id}`,{method:"DELETE"});if(response.ok){if(editingId===article.id)reset();await load()}else{const payload=await response.json();setNotice(payload.error||"Unable to delete article.")}}
  return <main className="article-admin"><header className="admin-top"><div><span>MH</span><div><strong>Article Studio</strong><small>Dr. Mohamad El Haress</small></div></div><div><span>{userName}</span><a href={signOutHref}>Sign out</a></div></header><div className="admin-shell">
    <section className="admin-editor"><div className="admin-editor-head"><div><span>{editingId?"Editing article":"New article"}</span><h1>{editingId?"Refine and republish.":"Create medical guidance."}</h1></div>{editingId&&<button onClick={reset}>+ New article</button>}</div>{notice&&<div className="admin-notice">{notice}</div>}
      <div className="admin-form-grid"><label className="wide"><span>Article title</span><input value={form.title} onChange={e=>{update("title",e.target.value);if(!editingId){update("slug",autoSlug(e.target.value));update("seoTitle",e.target.value);update("imageAlt",e.target.value)}}} placeholder="Enter a clear, patient-friendly title"/></label><label><span>URL slug · SEO</span><input value={form.slug} onChange={e=>update("slug",autoSlug(e.target.value))}/></label><label><span>Category</span><select value={form.category} onChange={e=>update("category",e.target.value)}><option>Patient Education</option><option>Patient guide</option><option>General Surgery</option><option>Surgical Oncology</option><option>Research Publication</option><option>Recovery</option><option>Second Opinion</option><option>Before Surgery</option></select></label><label><span>Reading time</span><input value={form.readTime} onChange={e=>update("readTime",e.target.value)} placeholder="5 min read"/></label><label><span>Author</span><input value={form.author} onChange={e=>update("author",e.target.value)} /></label><label><span>Existing image</span><select value={covers.some(([,path])=>path===form.coverImage)?form.coverImage:""} onChange={e=>e.target.value&&update("coverImage",e.target.value)}><option value="">Uploaded custom image</option>{covers.map(([name,path])=><option key={path} value={path}>{name}</option>)}</select></label><div className="admin-cover-upload"><span>Cover image</span><div className="admin-cover-preview"><img src={form.coverImage} alt="Article cover preview"/></div><label><input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0])}/>{uploading?"Uploading…":"Upload image from device"}</label><small>JPG, PNG or WebP · Maximum 8 MB</small></div><label className="wide"><span>Image alternative text</span><input value={form.imageAlt} onChange={e=>update("imageAlt",e.target.value)} placeholder="Describe the image for accessibility and search"/></label><label className="wide"><span>Introduction</span><textarea rows={3} value={form.lead} onChange={e=>update("lead",e.target.value)} placeholder="A concise introduction shown in article cards."/></label><label className="wide"><span>Key takeaway</span><textarea rows={2} value={form.takeaway} onChange={e=>update("takeaway",e.target.value)} placeholder="The single most important message for the reader."/></label></div>
      <div className="admin-block admin-seo"><div><span>Search & AI discoverability</span><small>Used by Google, Bing and AI-powered search systems</small></div><div className="admin-form-grid"><label className="wide"><span>SEO title · maximum 70 characters</span><input maxLength={70} value={form.seoTitle} onChange={e=>update("seoTitle",e.target.value)}/><small>{form.seoTitle.length}/70</small></label><label className="wide"><span>Meta description · maximum 170 characters</span><textarea rows={3} maxLength={170} value={form.metaDescription} onChange={e=>update("metaDescription",e.target.value)}/><small>{form.metaDescription.length}/170</small></label><label className="wide"><span>Keywords · separated by commas</span><input value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder="general surgery Lebanon, surgical oncology Beirut"/></label></div></div>
      <div className="admin-block"><div><span>At a glance</span><button onClick={()=>update("highlights",[...form.highlights,""])}>+ Add point</button></div>{form.highlights.map((item,index)=><div className="admin-repeat" key={index}><b>{String(index+1).padStart(2,"0")}</b><input value={item} onChange={e=>update("highlights",form.highlights.map((value,i)=>i===index?e.target.value:value))} placeholder="Short practical highlight"/>{form.highlights.length>1&&<button aria-label="Remove point" onClick={()=>update("highlights",form.highlights.filter((_,i)=>i!==index))}>×</button>}</div>)}</div>
      <div className="admin-block admin-writer"><div><span>Article content</span><small>Use <b>##</b> before a line to create a section heading</small></div><textarea rows={24} value={body} onChange={e=>setBody(e.target.value)} placeholder={`Write the complete article here comfortably.\n\nUse blank lines between paragraphs.\n\n## First section heading\n\nWrite the section text here.\n\n## Next section heading\n\nContinue writing...`}/><div className="writer-help"><span>Paragraphs</span><p>Leave one empty line between paragraphs. The website will format them automatically.</p><span>Headings</span><p>Start a heading with <b>##</b> followed by the title.</p></div></div>
      <div className="admin-actions"><button disabled={saving} onClick={()=>void save("draft")}>Save draft</button>{form.slug&&<a className="admin-preview-link" href={`/articles/${form.slug}`} target="_blank">Preview current page ↗</a>}<button disabled={saving} onClick={()=>void save("published")}>{saving?"Saving…":editingId&&form.status==="published"?"Update published article":"Publish article"} <b>→</b></button></div>
    </section>
    <aside className="admin-library"><div className="admin-library-head"><div><span>Content library</span><h2>{articles.length} articles</h2></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search articles"/></div>{loading?<p className="admin-empty">Loading articles…</p>:filtered.length===0?<p className="admin-empty">No articles found.</p>:<div className="admin-article-list">{filtered.map(article=>{const builtIn=article.id<0;return <article key={article.id}><div><span className={article.status}>{article.status}</span><small>{builtIn?"Built-in publication":article.category}</small></div><h3>{article.title}</h3><p>/{article.slug}</p><div><button onClick={()=>edit(article)}>Edit</button><a href={`/articles/${article.slug}`} target="_blank">View ↗</a>{!builtIn&&<button className="danger" onClick={()=>void remove(article)}>Delete</button>}</div></article>})}</div>}</aside>
  </div></main>
}
