"use client";
import { FormEvent, useState } from "react";

export function AppointmentForm(){
  const [consent,setConsent]=useState(false);
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault(); const data=new FormData(e.currentTarget); const val=(key:string)=>String(data.get(key)||"").trim();
    const message=["Hello, I would like to request an appointment with Dr. Mohamad El Haress.","",`Patient name: ${val("name")}`,`Phone number: ${val("phone")}`,`Preferred contact: ${val("contact")}`,`Consultation type: ${val("type")}`,`Preferred day: ${val("day")||"Flexible"}`,`Preferred time: ${val("time")||"Flexible"}`,"",`Reason for consultation: ${val("reason")}`,"",`Previous reports or imaging available: ${val("records")}`,"", "Please let me know the available appointment times. Thank you."];
    window.open(`https://wa.me/9613600777?text=${encodeURIComponent(message.join("\n"))}`,"_blank","noopener,noreferrer");
  }
  return <form className="booking-form" onSubmit={submit}><div className="form-heading"><span>Appointment request</span><h2>Patient details</h2><p>Fields marked * are required.</p></div><div className="form-grid"><label className="full">Full name *<input name="name" required placeholder="Patient full name" autoComplete="name"/></label><label>Phone number *<input name="phone" type="tel" required placeholder="e.g. +961…" autoComplete="tel"/></label><label>Preferred contact *<select name="contact" required defaultValue="WhatsApp"><option>WhatsApp</option><option>Phone call</option></select></label><label className="full">Consultation type *<select name="type" required defaultValue=""><option value="" disabled>Select a consultation</option><option>General Surgery consultation</option><option>Surgical Oncology consultation</option><option>Second opinion</option><option>Post-operative follow-up</option><option>Other surgical concern</option></select></label><label>Preferred day<input name="day" type="date"/></label><label>Preferred time<select name="time" defaultValue="Flexible"><option>Flexible</option><option>Morning</option><option>Afternoon</option><option>Evening</option></select></label><label className="full">Reason for consultation *<textarea name="reason" required rows={5} placeholder="Briefly describe the reason for your appointment"/></label><fieldset className="full"><legend>Do you have previous medical reports or imaging? *</legend><label><input type="radio" name="records" value="Yes" required/> Yes</label><label><input type="radio" name="records" value="No"/> No</label></fieldset><label className="consent full"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span>I understand that submitting this request does not confirm an appointment and is not for medical emergencies.</span></label></div><button className="submit-button" type="submit" disabled={!consent}><span>Continue to WhatsApp</span><b>→</b></button><small className="form-foot">You will be able to review the prepared message before sending it.</small></form>
}
