import type { ArticleRecord } from "@/lib/article-types";

const now = "2026-08-11T00:00:00.000Z";

export const defaultArticles: ArticleRecord[] = [
  {
    id: -1,
    slug: "preparing-for-a-surgical-consultation",
    title: "Preparing for a surgical consultation",
    lead: "A little preparation can make your appointment clearer, more focused, and more useful.",
    category: "Patient guide",
    readTime: "6 min read",
    coverImage: "/dr-mohamad-el-haress-portrait.png",
    imageAlt: "Dr. Mohamad El Haress preparing for a surgical consultation",
    takeaway: "A productive consultation begins with complete information and ends with a next step you clearly understand.",
    highlights: ["Bring reports, imaging and medication lists", "Prepare your most important questions", "Ask for the plan to be explained clearly"],
    sections: [
      { title: "Bring the full clinical picture", body: "Collect relevant medical reports, imaging, laboratory results, pathology reports, a list of medications, allergies, and details of previous operations." },
      { title: "Write down your questions", body: "Consider what you want to understand about the diagnosis, whether surgery is necessary, available alternatives, expected recovery, and what happens next." },
      { title: "Leave with a clear next step", body: "Before the visit ends, make sure you understand the recommended plan, any additional tests, warning signs, and how follow-up will be arranged." },
    ],
    status: "published",
    author: "Dr. Mohamad El Haress",
    seoTitle: "Preparing for a Surgical Consultation | Dr. Mohamad El Haress",
    metaDescription: "How to prepare reports, imaging, medication lists and questions for a productive surgical consultation.",
    keywords: ["surgical consultation", "surgeon appointment", "surgery preparation Lebanon"],
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
  },
  {
    id: -2,
    slug: "surgery-in-cancer-care",
    title: "The role of surgery in multidisciplinary cancer care",
    lead: "Cancer treatment may involve several specialists and more than one type of treatment.",
    category: "Surgical Oncology",
    readTime: "7 min read",
    coverImage: "/article-multidisciplinary-cancer-care.png",
    imageAlt: "Multidisciplinary cancer care team discussing a personalized treatment plan",
    takeaway: "The strongest cancer plan is coordinated: surgery, pathology, imaging and oncology decisions should support one another.",
    highlights: ["Treatment sequence matters", "Every operation needs a defined purpose", "Questions are an essential part of consent"],
    sections: [
      { title: "Why coordination matters", body: "The sequence of surgery, systemic treatment, and radiotherapy can influence outcomes." },
      { title: "What a surgical oncologist considers", body: "A consultation explores whether an operation is appropriate, its intended purpose, possible risks, and anticipated recovery." },
      { title: "Your role in the conversation", body: "Patients should feel able to ask why a treatment is recommended, whether alternatives exist, and how the plan may affect daily life." },
    ],
    status: "published",
    author: "Dr. Mohamad El Haress",
    seoTitle: "Surgery in Multidisciplinary Cancer Care | Dr. Mohamad El Haress",
    metaDescription: "How surgical oncology, medical oncology, radiology and pathology work together in cancer treatment planning.",
    keywords: ["multidisciplinary cancer care", "surgical oncology Lebanon", "cancer surgery Beirut"],
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
  },
  {
    id: -3,
    slug: "after-surgery-recovery",
    title: "After surgery: supporting a safer recovery",
    lead: "Recovery differs for every person and procedure. Your clinical team’s instructions should always guide your care.",
    category: "Recovery",
    readTime: "5 min read",
    coverImage: "/article-after-surgery-recovery.png",
    imageAlt: "Patient resting safely at home during recovery after surgery",
    takeaway: "Recovery is not a race. Follow the individualized plan, make steady progress and know which changes require medical attention.",
    highlights: ["Follow your discharge instructions", "Return to activity gradually", "Know the warning signs that need help"],
    sections: [
      { title: "Follow your discharge plan", body: "Take medications as directed, care for the wound as instructed, attend follow-up, and understand restrictions." },
      { title: "Support steady progress", body: "Appropriate movement, hydration, nutrition, sleep, and gradual activity can support recovery when allowed by your surgeon." },
      { title: "Know when to seek help", body: "Contact your care team for concerning changes. Severe symptoms or rapid deterioration require urgent medical attention." },
    ],
    status: "published",
    author: "Dr. Mohamad El Haress",
    seoTitle: "Recovery After Surgery | Dr. Mohamad El Haress",
    metaDescription: "Patient guidance for a safer recovery after surgery, including discharge instructions, activity and warning signs.",
    keywords: ["recovery after surgery", "postoperative care", "surgery recovery Lebanon"],
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
  },
];
