import type { ArticleRecord } from "./article-types";

const now="2026-08-13T00:00:00.000Z";
const records:[string,string,string,string,string,string[]][]=[
  ["iatrogenic-acute-ascending-aortic-dissection","Iatrogenic Acute Ascending Aortic Dissection with Intramural Hematoma during Coronary Artery Stenting: A Case Report","This case report examines a rare, life-threatening aortic complication occurring during coronary intervention.","10.3389/fsurg.2017.00002","The report emphasizes rapid recognition, accurate assessment of dissection extent, and urgent multidisciplinary management.",["Clinical background|Iatrogenic ascending aortic dissection during percutaneous coronary intervention is exceptionally rare but potentially fatal. The report describes an acute type A dissection with intramural hematoma arising during elective coronary stenting.","Case and management|The patient was transferred urgently for surgical repair. Management included replacement of the affected ascending aorta together with coronary revascularization, followed by successful recovery.","Clinical relevance|The case highlights careful catheter manipulation, immediate recognition of aortic injury, and treatment decisions based on hemodynamic stability and the extent of aortic involvement."]],
  ["giant-ureteral-fibroepithelial-polyp","Giant Ureteral Fibroepithelial Polyp with Intermittent Prolapse Reaching the Urethral Meatus: A Case Report","A rare benign ureteral polyp with an unusual presentation and successful endoscopic treatment.","10.1016/j.eucr.2017.03.015","A very uncommon presentation was treated with complete ureteroscopic resection while preserving urinary function.",["Unusual presentation|A 37-year-old woman presented with urinary symptoms and an intermittently protruding mass. Investigation identified a giant fibroepithelial polyp originating from the distal ureter.","Diagnosis and treatment|Endoscopic examination, imaging, and pathology confirmed the benign lesion. Ureteroscopic electrocautery enabled complete resection followed by temporary ureteral stenting.","Clinical relevance|The case demonstrates the importance of considering benign ureteral lesions in unusual urinary presentations and shows how endoscopic treatment may avoid more extensive surgery."]],
  ["neuroproteomics-studies-challenges-updates","Neuroproteomics Studies: Challenges and Updates","A methods-focused overview of the opportunities and technical challenges involved in studying the nervous system proteome.","10.1007/978-1-4939-6952-4_1","Neuroproteomics requires carefully selected samples, rigorous analytical methods, and thoughtful interpretation of complex molecular data.",["Field overview|Neuroproteomics applies protein-analysis technologies to the brain, spinal cord, peripheral nerves, and related biological systems.","Methodological challenges|Nervous-system tissue is highly complex and dynamic. Sample quality, cellular diversity, protein abundance, post-translational modification, and analytical reproducibility all influence results.","Research value|Improved proteomic methods can support biomarker discovery, disease-mechanism research, and the development of more precise neurological investigations."]],
  ["chyle-leak-after-laparoscopic-cholecystectomy","Diagnosis and Treatment of a 64-Year-Old Man with Chyle Leak Following Laparoscopic Cholecystectomy: A Case Report","A rare postoperative chyle leak after gallbladder surgery and the diagnostic and treatment pathway used to manage it.","10.12659/AJCR.943429","Persistent unusual drainage after surgery requires structured investigation and treatment tailored to the patient’s clinical course.",["Clinical presentation|The report describes a 64-year-old man who developed a chyle leak following laparoscopic cholecystectomy, an uncommon complication after this procedure.","Diagnostic approach|The character of the drainage, laboratory analysis, imaging, and clinical evolution helped establish the diagnosis and exclude other postoperative complications.","Management lessons|The case illustrates stepwise management and the importance of recognizing rare complications early while adapting treatment to the volume and persistence of the leak."]],
  ["laparoscopic-large-colonic-lipoma","Laparoscopic Management of Large Colonic Lipoma with Atypical Presentation: A Case Report","A large benign colonic lipoma presenting atypically and managed through a minimally invasive surgical approach.","10.1016/j.ijscr.2024.110281","Large symptomatic colonic lipomas can resemble other lesions and require careful diagnostic and operative planning.",["Diagnostic challenge|Colonic lipomas are generally benign and often incidental, but large lesions may produce pain, obstruction, bleeding, or an atypical radiologic appearance.","Surgical management|The case describes laparoscopic treatment selected after clinical, endoscopic, and imaging assessment of the lesion.","Clinical relevance|The report reinforces the role of minimally invasive surgery for selected large or symptomatic benign colonic tumors when endoscopic treatment is unsuitable."]],
  ["alexis-wound-protector-perianal-oncologic-surgery","Use of the Alexis® Wound Protector for Exposure and Sterility in Perianal Oncologic Surgery: A Technical Report","A practical surgical technique using a wound protector to support exposure and sterility in perianal oncologic surgery.","10.7759/cureus.104190","Adapting a familiar surgical device may improve operative access and protect the field during technically demanding perianal surgery.",["Technical problem|Perianal oncologic procedures can present challenges related to exposure, tissue handling, and contamination of the operative field.","Technique|The report describes positioning an Alexis wound protector to retract tissue circumferentially and create a cleaner, more accessible working field.","Potential value|The approach offers a practical and reproducible option that may support visualization, sterility, and workflow in selected perianal operations."]],
  ["appendicitis-following-colonoscopy","Beyond the Scope: Unmasking Appendicitis Following Colonoscopy","A report exploring acute appendicitis occurring after colonoscopy and the importance of recognizing uncommon post-procedure symptoms.","10.7759/cureus.106922","New or worsening right-sided abdominal pain after colonoscopy should not automatically be attributed to routine post-procedure discomfort.",["Clinical context|Abdominal discomfort after colonoscopy is common, but appendicitis is an uncommon and potentially serious diagnosis in this setting.","Assessment|Persistent focal pain and evolving clinical findings require appropriate examination, laboratory evaluation, and imaging rather than reassurance alone.","Clinical lesson|The report encourages awareness of rare post-colonoscopy complications so that appendicitis can be identified and treated promptly."]],
  ["enucleation-giant-hepatic-hemangiomas","Open Parenchyma-Preserving Enucleation of Giant Hepatic Hemangiomas: A Systematic CUSA-Guided Pringle-Free Technique","A liver-preserving operative technique for selected giant hepatic hemangiomas.","10.7759/cureus.106383","Careful enucleation may remove selected giant hemangiomas while preserving healthy liver tissue and limiting interruption of blood flow.",["Surgical objective|Giant hepatic hemangiomas may require treatment when symptomatic, complicated, or diagnostically uncertain. Preserving normal liver parenchyma is an important operative goal.","Operative technique|The report presents a systematic open enucleation technique guided by ultrasonic aspiration without routine Pringle inflow occlusion.","Clinical relevance|The approach emphasizes precise dissection along the tumor plane, control of vascular structures, and preservation of functioning liver tissue."]],
  ["atypical-retroperitoneal-tumor","An Atypical Presentation of a Retroperitoneal Tumor: A Case Report","An unusual retroperitoneal tumor presentation illustrating the diagnostic complexity of deep abdominal masses.","10.1016/j.hmedic.2026.100429","Retroperitoneal tumors often require cross-sectional imaging, pathology review, and carefully coordinated surgical planning.",["Presentation|Retroperitoneal tumors can grow silently and may present with nonspecific symptoms or unexpected findings.","Diagnostic pathway|Detailed CT or MRI evaluation helps define the mass, its relationship to adjacent organs and vessels, and whether biopsy or surgery is appropriate.","Clinical relevance|The report highlights individualized decision-making for rare tumors in anatomically complex locations."]],
  ["inflamed-canal-of-nuck-cyst","An Unusual Diagnosis of Inguinal Pain in a Childbearing-Age Woman: An Inflamed Canal of Nuck Cyst With an Abnormal Leiomyomatous Proliferation","A rare cause of female inguinal pain involving an inflamed canal of Nuck cyst with unusual pathology.","10.7759/cureus.109199","A broad differential diagnosis and pathology review are essential when an inguinal mass has an atypical presentation.",["Clinical presentation|A woman of childbearing age presented with inguinal pain and a mass that required differentiation from a hernia and other groin conditions.","Diagnosis and pathology|Surgical assessment identified an inflamed canal of Nuck cyst with abnormal leiomyomatous proliferation, an uncommon combination.","Clinical lesson|The case demonstrates how imaging, operative findings, and histopathology work together to establish the diagnosis of unusual groin lesions."]],
  ["serrated-polyposis-small-large-bowel","Incidental Diagnosis of Serrated Polyposis Syndrome of the Small and Large Bowel Treated Endoscopically and Surgically: A Case Report","A rare presentation of extensive serrated polyposis managed through coordinated endoscopic and surgical treatment.","10.7759/cureus.108912","Complex polyposis may require combined endoscopic surveillance, pathology assessment, and individualized surgery.",["Incidental diagnosis|Serrated polyposis syndrome can be discovered during investigation or screening and carries implications for colorectal cancer risk and long-term surveillance.","Combined management|The reported disease involved the small and large bowel and required collaboration between endoscopy, pathology, and surgery.","Clinical relevance|The case supports tailoring treatment to polyp burden, distribution, pathology, and the feasibility of endoscopic clearance."]],
  ["sphincter-preserving-resection-perianal-gist","Sphincter-Preserving Intersphincteric Resection for Perianal GIST Following Neoadjuvant Imatinib: Case Report and Literature Review","A multidisciplinary, organ-preserving strategy for a rare perianal gastrointestinal stromal tumor.","10.1016/j.hmedic.2026.100475","Careful treatment sequencing may make oncologically sound, sphincter-preserving surgery possible in selected perianal GIST cases.",["Rare tumor location|Perianal gastrointestinal stromal tumors are uncommon and present difficult decisions because of their proximity to the anal sphincter complex.","Treatment sequence|Neoadjuvant imatinib was used to support tumor downsizing before planning an intersphincteric resection.","Clinical relevance|The report illustrates multidisciplinary planning that balances tumor clearance with preservation of continence and quality of life."]]
];

const researchCovers = [
  "/articles/research/iatrogenic-acute-ascending-aortic-dissection.jpg",
  "/articles/research/giant-ureteral-fibroepithelial-polyp.jpg",
  "/articles/research/neuroproteomics-studies-challenges-updates.webp",
  "/articles/research/chyle-leak-after-laparoscopic-cholecystectomy.webp",
  "/articles/research/laparoscopic-large-colonic-lipoma.jpg",
  "/articles/research/alexis-wound-protector-perianal-oncologic-surgery.webp",
  "/articles/research/appendicitis-following-colonoscopy.jpg",
  "/articles/research/enucleation-giant-hepatic-hemangiomas.jpg",
  "/articles/research/atypical-retroperitoneal-tumor.jpg",
  "/dr-haress-surgery-team.png",
  "/articles/research/serrated-polyposis-small-large-bowel.jpg",
  "/articles/research/sphincter-preserving-resection-perianal-gist.jpg",
];

export const researchArticles:ArticleRecord[]=records.map(([slug,title,lead,doi,takeaway,raw],index)=>({id:-100-index,slug,title,lead,category:"Research Publication",readTime:"Research summary",coverImage:researchCovers[index],imageAlt:`Medical publication visual for ${title}`,takeaway,highlights:[`DOI: ${doi}`,"Authored or co-authored by Dr. Mohamad El Haress","Research summary prepared for this professional profile"],sections:raw.map(value=>{const [sectionTitle,body]=value.split("|");return{title:sectionTitle,body:`${body}\n\nPublication identifier: DOI ${doi}.`}}),status:"published",author:"Dr. Mohamad El Haress",seoTitle:title,metaDescription:lead,keywords:["Dr. Mohamad El Haress publication","surgical research",doi],createdAt:now,updatedAt:now,publishedAt:now}));
