import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";

type PageData = { eyebrow: string; title: string; intro: string; image: string; imageAlt: string; highlight: string; sections: { title: string; text: string; items?: string[] }[] };

const pages: Record<string, PageData> = {
  "about": { eyebrow: "About Dr. Haress", title: "A considered approach to surgical care.", intro: "Dr. Mohamad El Haress provides specialist care in general surgery and surgical oncology, with an emphasis on careful evaluation, clear explanations, and patient-centered planning.", image: "/dr-mohamad-el-haress-portrait.png", imageAlt: "Dr. Mohamad El Haress", highlight: "Care built around the individual", sections: [
    { title: "The person behind the diagnosis", text: "A surgical consultation should create clarity, not confusion. Every visit begins by listening carefully, reviewing the available information, and understanding what matters to the patient and family." },
    { title: "Thoughtful clinical decisions", text: "Recommendations are made with respect for the full clinical picture. When surgery is appropriate, the purpose, expected course, alternatives, and recovery are discussed in direct, understandable language." },
    { title: "Credentials", text: "General Surgery · Surgical Oncology", items: ["General surgical assessment", "Surgical oncology consultation", "Pre-operative planning", "Post-operative follow-up"] }
  ]},
  "general-surgery": { eyebrow: "General Surgery", title: "Precision at every stage of surgical care.", intro: "Comprehensive evaluation, modern surgical techniques and individualized planning—from the first consultation through recovery.", image: "/dr-haress-operating.png", imageAlt: "Dr. Mohamad El Haress performing surgery", highlight: "Advanced laparoscopic & general surgery", sections: [
    { title: "A clear path from assessment to recovery", text: "The process begins with a detailed consultation and review of symptoms, medical history, examinations, and available imaging. The goal is to identify the safest and most appropriate next step." },
    { title: "Minimally invasive surgery", text: "Laparoscopic techniques may support smaller incisions and recovery when clinically appropriate.", items: ["Laparoscopic gallbladder removal", "Laparoscopic appendix removal", "Laparoscopic hernia repair", "Weight loss surgery", "Treatment of abdominal tumors"] },
    { title: "General surgery services", text: "Each service begins with specialist evaluation. The appropriate approach depends on the individual diagnosis and overall health.", items: ["Thyroid and breast surgery", "Stomach and intestinal conditions", "Emergency abdominal surgery", "Liver and pancreatic surgery", "Other complex abdominal conditions", "Post-operative care"] },
    { title: "When to request a consultation", text: "Seek medical attention for persistent or worsening symptoms, a new diagnosis that may require surgery, or when you would like a specialist surgical opinion. Urgent symptoms require immediate emergency care." }
  ]},
  "surgical-oncology": { eyebrow: "Surgical Oncology", title: "Cancer surgery planned around the whole patient.", intro: "Exact planning, multidisciplinary thinking and honest communication for patients and families navigating a cancer diagnosis.", image: "/dr-haress-surgery-team.png", imageAlt: "Surgical oncology team in the operating room", highlight: "Complex cancer care with a human focus", sections: [
    { title: "Surgery within a complete cancer plan", text: "The role and timing of surgery are considered alongside the diagnosis, stage, pathology, imaging, and other recommended treatments. Coordination with the wider care team helps keep decisions aligned." },
    { title: "Cancer surgery expertise", text: "A consultation may include review of existing reports and imaging, discussion of the purpose of surgery, and a clear explanation of expected next steps.", items: ["Breast and thyroid cancer surgery", "Gastrointestinal cancer surgery", "Tumor removal and lymph node surgery", "Debulking surgery", "HIPEC", "Multidisciplinary oncology support"] },
    { title: "Information with sensitivity", text: "Patients deserve information they can understand and time to ask questions. Family members may be included in discussions when the patient wishes." }
  ]},
  "services": { eyebrow: "Procedures & Services", title: "A complete surgical care pathway.", intro: "Specialist consultations, advanced procedures and structured follow-up designed around sound clinical judgment and continuity of care.", image: "/dr-haress-operating-room.png", imageAlt: "Dr. Mohamad El Haress in surgery", highlight: "From diagnosis to confident recovery", sections: [
    { title: "Consultations", text: "Focused specialist appointments for new symptoms, an existing diagnosis, a second surgical opinion, or review of a proposed treatment plan.", items: ["Initial surgical consultation", "Second opinion", "Review of imaging and reports", "Pre-operative evaluation"] },
    { title: "Minimally invasive surgery", text: "Advanced laparoscopic care when appropriate for the diagnosis and patient.", items: ["Gallbladder removal", "Appendix removal", "Hernia repair", "Weight loss surgery", "Treatment of abdominal tumors"] },
    { title: "General & cancer surgery", text: "Procedure selection is based on diagnosis and patient-specific considerations.", items: ["Thyroid and breast surgery", "Stomach and intestinal surgery", "Liver and pancreatic surgery", "Emergency abdominal surgery", "Cancer resection and lymph node surgery", "Debulking surgery and HIPEC"] },
    { title: "Recovery & additional care", text: "Structured post-surgery follow-up, recovery guidance, discussion of treatment options, and healthy lifestyle support." }
  ]},
  "contact": { eyebrow: "Contact the Clinic", title: "Your consultation starts with a clear conversation.", intro: "For appointments and clinic enquiries, contact the office directly or send a prepared appointment request through WhatsApp.", image: "/dr-haress-surgery-portrait.png", imageAlt: "Dr. Mohamad El Haress in the operating room", highlight: "Specialist consultations by appointment", sections: [
    { title: "Speak with the clinic", text: "+961 03 600 777", items: ["Consultations by appointment", "Lebanon", "WhatsApp appointment requests available"] },
    { title: "Before your visit", text: "Please bring your identification, current medications, previous medical reports, pathology results, and relevant imaging. Having these available can help make the consultation more useful." },
    { title: "Urgent concerns", text: "This website and WhatsApp appointment service are not monitored for emergencies. If you have severe or rapidly worsening symptoms, contact local emergency services or visit the nearest emergency department." }
  ]}
};

export async function generateStaticParams() { return Object.keys(pages).map(slug => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{slug:string}> }): Promise<Metadata> { const { slug } = await params; const page=pages[slug]; return page ? { title: page.title, description: page.intro, alternates:{canonical:`/${slug}`}, openGraph:{title:page.title,description:page.intro,type:"website",url:`/${slug}`}, keywords:[page.eyebrow,"Dr Mohamad El Haress",`${page.eyebrow} Lebanon`,`${page.eyebrow} Beirut`] } : {}; }

export default async function InfoPage({ params }: { params: Promise<{slug:string}> }) {
  const {slug}=await params; const page=pages[slug]; if(!page) notFound();
  const primary = page.sections[0];
  const serviceSections = page.sections.slice(1);
  return <main id="main" className={`specialty-page specialty-${slug}`}>
    <section className="specialty-hero"><div className="container specialty-hero-grid"><div className="specialty-hero-copy"><div className="eyebrow light"><span></span>{page.eyebrow}</div><h1>{page.title}</h1><p>{page.intro}</p><div className="specialty-actions"><Link className="button white" href="/appointment">Request appointment <b>→</b></Link><a href="tel:+9613600777">Call the clinic <b>↗</b></a></div></div><div className="specialty-hero-visual"><Image src={page.image} alt={page.imageAlt} fill sizes="(max-width:760px) 100vw, 46vw" priority unoptimized/><div className="specialty-image-label"><span>Dr. Mohamad El Haress</span><strong>{page.highlight}</strong></div></div></div></section>

    <section className="specialty-overview"><div className="container specialty-overview-grid"><div><span>01 · The approach</span><h2>{primary.title}</h2></div><div><p>{primary.text}</p><div className="care-principles"><article><b>01</b><strong>Detailed evaluation</strong><span>A complete clinical picture before decisions are made.</span></article><article><b>02</b><strong>Clear planning</strong><span>Options, purpose and expectations explained directly.</span></article><article><b>03</b><strong>Continued care</strong><span>Guidance from preparation through follow-up.</span></article></div></div></div></section>

    <section className="specialty-services"><div className="container"><div className="specialty-section-head"><div><div className="eyebrow"><span></span>Scope of care</div><h2>Specialized expertise.<br/><em>Thoughtfully delivered.</em></h2></div><p>Every recommendation follows specialist evaluation and is tailored to the diagnosis, health and priorities of the individual patient.</p></div><div className="specialty-card-grid">{serviceSections.map((section,index)=><article key={section.title} className={index===0?"featured-service":""}><div className="service-card-top"><span>{String(index+2).padStart(2,"0")}</span><i>+</i></div><h3>{section.title}</h3><p>{section.text}</p>{section.items&&<ul>{section.items.map(item=><li key={item}>{item}</li>)}</ul>}</article>)}</div></div></section>

    <section className="care-path"><div className="container"><div className="care-path-intro"><span>Your care pathway</span><h2>Clarity from consultation to recovery.</h2></div><div className="care-path-steps"><article><span>01</span><h3>Consultation</h3><p>Review symptoms, records, imaging and what matters most to you.</p></article><article><span>02</span><h3>Personalized plan</h3><p>Understand the diagnosis, options, benefits and expected next steps.</p></article><article><span>03</span><h3>Surgical care</h3><p>Precise, safety-focused treatment using the appropriate approach.</p></article><article><span>04</span><h3>Recovery</h3><p>Structured follow-up and practical guidance throughout healing.</p></article></div></div></section>

    <section className="specialty-reassurance"><div className="container"><div className="reassurance-image"><Image src="/dr-haress-operating-room.png" alt="Dr. Mohamad El Haress providing surgical care" fill sizes="(max-width:760px) 100vw, 48vw" unoptimized/></div><div className="reassurance-copy"><div className="eyebrow"><span></span>Patient-centered decisions</div><h2>Technical excellence is only part of exceptional care.</h2><blockquote>“Every patient deserves to understand their options and feel supported through each decision.”</blockquote><p>Questions are welcomed. Recommendations are explained in direct language, with time for patients and families to understand the plan and prepare for what comes next.</p><Link className="inline-link" href="/about">Meet Dr. Haress <b>→</b></Link></div></div></section>

    <section className="specialty-cta"><div className="container"><div><span>Specialist surgical consultation</span><h2>Let’s discuss the right next step for your care.</h2></div><Link className="button white" href="/appointment">Request an appointment <b>→</b></Link></div></section>
  </main>;
}
