import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { getPublishedArticles } from "@/lib/article-data";

export const dynamic="force-dynamic";
export const revalidate=0;
export const metadata:Metadata={title:"Medical Articles",description:"Clear, reliable patient education about surgery, surgical oncology, and recovery.",alternates:{canonical:"/articles"}};

export default async function Articles(){const articles=await getPublishedArticles();const featured=articles[0];const rest=articles.slice(1);return <main id="main"><section className="journal-hero"><div className="container"><div><div className="eyebrow light"><span></span>Patient education & research</div><h1>Medical knowledge.<br/><em>Made clear.</em></h1></div><p>Evidence-informed guidance for patients and families, together with research publications authored or co-authored by Dr. El Haress.</p></div></section><section className="journal-index"><div className="container"><div className="journal-toolbar"><span>Insights from Dr. Haress</span><div><b>All articles</b><span>General Surgery</span><span>Surgical Oncology</span><span>Research</span><span>Recovery</span></div></div>{featured?<><Link className="featured-story database-featured" href={`/articles/${featured.slug}`}><div className="journal-photo"><Image src={featured.coverImage} alt={featured.imageAlt||featured.title} fill sizes="(max-width:760px) 100vw, 52vw" priority unoptimized/><span>Featured article</span></div><div className="featured-copy"><small>{featured.category}</small><h2>{featured.title}</h2><p>{featured.lead}</p><div><span>{featured.readTime}</span><b>Read the article <i>→</i></b></div></div></Link><div className="journal-grid database-grid">{rest.map(article=><Link className="journal-card" href={`/articles/${article.slug}`} key={article.id}><div className="journal-card-photo"><Image src={article.coverImage} alt={article.imageAlt||article.title} fill sizes="(max-width:760px) 100vw, 33vw" unoptimized/></div><div className="journal-card-copy"><small>{article.category}</small><h2>{article.title}</h2><p>{article.lead}</p><div><span>{article.readTime}</span><b>Read →</b></div></div></Link>)}</div></>:<div className="journal-empty"><h2>Medical articles are being prepared.</h2><p>Please check back soon for new patient education from Dr. Haress.</p></div>}<div className="journal-note"><div><span>Looking for personal guidance?</span><h2>Articles inform. A consultation makes it personal.</h2></div><Link className="button primary" href="/appointment">Request an appointment <b>→</b></Link></div></div></section></main>}
